package service.validation;

public enum ErrorKey {
    EMPTY_LOGIN,
    INCORRECT_STRUCTURE_LOGIN,
    EMPTY_EMAIL,
    INCORRECT_EMAIL,
    EMPTY_RHOHENUM,
    INCORRECT_PHONENUM,
    EMPTY_PASSWORD,
    INCORRECT_PASSWORD,
    LOGIN_EXIST,
    EMAIL_EXIST,
    TELNUM_EXIST
}
